spring:
  profiles:
    active: dev
  freemarker:
    suffix: .html
mybatis:
  type-aliases-package: com.showtime.sign.model.entity
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

