DROP DATABASE IF EXISTS sign;
/*创建数据库，并设置编码*/
CREATE DATABASE sign DEFAULT CHARACTER SET utf8mb4;

USE sign;

DROP TABLE IF EXISTS `admin`;
CREATE TABLE IF NOT EXISTS `admin`(
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '表主键',

  `account` VARCHAR(64) UNIQUE NOT NULL COMMENT '账号',
  `password` VARCHAR(64) COMMENT '密码',
  `salt` VARCHAR(64) COMMENT '盐'
)ENGINE INNODB DEFAULT CHARSET=utf8 COMMENT='管理员' AUTO_INCREMENT=1;

DROP TABLE IF EXISTS `teachers`;
CREATE TABLE IF NOT EXISTS `teachers`(
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '表主键',

  `account` VARCHAR(64) UNIQUE NOT NULL COMMENT '账号',
  `password` VARCHAR(64) COMMENT '密码',
  `salt` VARCHAR(64) COMMENT '盐'
)ENGINE INNODB DEFAULT CHARSET=utf8 COMMENT='教师' AUTO_INCREMENT=1;

DROP TABLE IF EXISTS `students`;
CREATE TABLE IF NOT EXISTS `students`(
  `id` BIGINT UNSIGNED PRIMARY KEY COMMENT '表主键',

  `account` VARCHAR(64) UNIQUE NOT NULL COMMENT '账号',
  `name` VARCHAR(64) COMMENT '姓名',
  `class_name` VARCHAR(64) COMMENT '班级',
  `password` VARCHAR(64) COMMENT '密码',
  `salt` VARCHAR(64) COMMENT '盐'
)ENGINE INNODB DEFAULT CHARSET=utf8 COMMENT='学生' AUTO_INCREMENT=1;

DROP TABLE IF EXISTS `courses`;
CREATE TABLE IF NOT EXISTS `courses`(
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '表主键',

  `semester` VARCHAR(64) UNIQUE NOT NULL COMMENT '学年学期',
  `number` INT UNIQUE NOT NULL COMMENT '开课编号',
  `name` VARCHAR(64) COMMENT '课程名称',
  `classes` VARCHAR(64) COMMENT '教学班名称',
  `teacher` VARCHAR(64) COMMENT '授课教师',
  `jieci` INT COMMENT '节次',
  `sign_state` TINYINT COMMENT '签到状态， 0:未开始 1：已完成 2：签到中',
  `date` DATE COMMENT '日期'
)ENGINE INNODB DEFAULT CHARSET=utf8 COMMENT='课程' AUTO_INCREMENT=1;

DROP TABLE IF EXISTS `sign_detil`;
CREATE TABLE IF NOT EXISTS `sign_detil`(
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '表主键',

  `student_id` BIGINT UNSIGNED UNIQUE NOT NULL COMMENT '签到学生',
  `class_name` VARCHAR(64) COMMENT '班级名称',
  `student_name` VARCHAR(64) COMMENT '学生姓名',
  `course_number` BIGINT UNSIGNED COMMENT '签到的课程',
  `sign_time` TIMESTAMP COMMENT '签到时间',
  `sign_state` TINYINT COMMENT '签到状态 0:未签到 1:签到成功 2：补签'
)ENGINE INNODB DEFAULT CHARSET=utf8 COMMENT='签到明细' AUTO_INCREMENT=1;

DROP TABLE IF EXISTS `sign_statistical`;
CREATE TABLE IF NOT EXISTS `sign_statistical`(
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '表主键',

  `student_id` BIGINT UNSIGNED UNIQUE NOT NULL COMMENT '签到学生',
  `class_name` VARCHAR(64) COMMENT '班级名称',
  `student_name` VARCHAR(64) COMMENT '学生姓名',
  `course_id` BIGINT UNSIGNED COMMENT '签到的课程',
  `sign_times` INT COMMENT '已经签到次数',
  `sign_need_times` INT COMMENT '需要签到次数'
)ENGINE INNODB DEFAULT CHARSET=utf8 COMMENT='签到统计' AUTO_INCREMENT=1;

DROP TABLE IF EXISTS `login_ticket`;
CREATE TABLE IF NOT EXISTS `login_ticket`(
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '表主键',

  `account_id` BIGINT UNSIGNED COMMENT '账户id',
  `role` TINYINT COMMENT '角色',
  `expired` DATETIME NOT NULL COMMENT '超时时间',
  `status` TINYINT NOT NULL DEFAULT '1' COMMENT '是否有效',
  `ticket` VARCHAR(64) NOT NULL COMMENT '票据'
)ENGINE INNODB DEFAULT CHARSET=utf8 COMMENT='token' AUTO_INCREMENT=1;